version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    # image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=FREE
      - ORACLE_PDB=BATATA
      - ORACLE_PWD=batata123

    ports:
      - 1521:1521
    networks:
      - backend
    # volumes:
    #   - oracle-data:/opt/oracle/oradata
    #   - oracle-backup:/opt/oracle/backup

  spring-api:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - oracle-db
  # volumes:
  #   oracle-data:
  #   oracle-backup:



networks:
  backend:
    name: backend
    driver: bridge
